### ISSUE TITLE
Failed to boot into reacovery fastboot mode 

### ISSUE THREAD

**Issue by andyshrk** [GloDroidCommunity/pine64-pinephonepro#4]
After update the latest code,  I failed to boot into the revovery fastboot mode.

Below is the boot log,  hope if you can give some advice.

https://pastebin.com/0yVauNL9

**Comment by rsglobal** [comment]
Please check the log: `cat /tmp/recovery.log`

**Comment by andyshrk** [comment]
recovery.log:
`
# cat /tmp/recovery.log                                                        
[    0.000714] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.000795] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.000805] E:Failed to read default fstab
[    0.000848] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.000861] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.000871] E:failed to read default fstab
[    0.000916] [    0.001114] libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 144 (recovery), pid 144
 (recovery)
[    0.001018] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.001746] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.002186] E:Failed to read default fstab
[    0.003352] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.004081] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.004568] E:failed to read default fstab
[    0.005065] [    0.005246] libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 152 (recovery), pid 152
 (recovery)
[    0.000983] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.001715] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.002146] E:Failed to read default fstab
[    0.003310] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.004056] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.004507] E:failed to read default fstab
[    0.005042] [    0.005216] libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 156 (recovery), pid 156
 (recovery)
[    0.000975] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.001774] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.002209] E:Failed to read default fstab
[    0.003331] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.004047] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.004542] E:failed to read default fstab
[    0.005041] [    0.005206] libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 160 (recovery), pid 160
 (recovery)
[    0.000353] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.000442] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.000453] E:Failed to read default fstab
[    0.000463] E:[libfs_mgr]ReadFstabFromFile(): failed to read file: '/etc/recovery.fstab': No such file or di
rectory
[    0.000472] I:[libfs_mgr]ReadDefaultFstab(): failed to find device default fstab
[    0.000481] E:failed to read default fstab
[    0.000490] [    0.000504] libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 164 (recovery), pid 164
 (recovery)
# 
`

**Comment by rsglobal** [comment]
That's strange. Have you tried removing the out/ directory and rebuilding from scratch?

**Comment by andyshrk** [comment]
when try to rebuild it, I see some error log about my computer's hard disk. Maybe the hard disk issue cause the recovery image error.

Anyway, I try to migrate to a new disk。

**Comment by andyshrk** [comment]
After migrate to a new disk and sync the dptx.bin copy path[0],
than i remove out and build it again, now is okay.


[0]https://github.com/andyshrk/pine64-pinephonepro/commit/19a435c96e8140a766a33fc17e7bc348da7b956a
