### ISSUE TITLE
Unable to Enter Bootloader Mode (PinePhone Pro)

### ISSUE THREAD

**Issue by MrMendelli** [GloDroidCommunity/pine64-pinephonepro#9]
I've been attempting to flash LineageOS for a few hours now with no luck and no real leads so I have opted to open an issue here.

I am attempting to flash LineageOS to EMMC, regardless of the OS or software I use to flash the image to the microSD card the device indicator LED never flashes blue and persistently boots into the stock OS. I ensured I downloaded the latest appropriate release and have attempted everything I can think of to no avail. I have tried multiple cards and I have also ensured that the physical hardware is working and that the disk can be read and written.

I had another regular PinePhone I purchased about a month ago and was able to flash easily, I have followed the official guide as well as the documentation I made for my own use the first time around when flashing this to the previous device. I would like to note that I haven't made any changes to the method or the new device.

I did purchase my device rather recently, so I do not know if Pine64  has perhaps updated something that requires an update on this project in accordance. I really need assistance or some answers as to why I can't seem to flash GloDroid to my new device. I am aware this is likely a hobby project upheld by volunteer work, so while I want some sort of answer or assistance I would like to emphasize that I am making no demands and appreciate everything this project and its contributors are doing.

**Comment by rsglobal** [comment]
Rockchip SOC which PPP is using has a different boot priority `eeprom, emmc, sd`. In contrast, the PP has: `sd, emmc`.
That means while you have working firmware on EEPROM or emmc, you won't be able to boot from a sdcard.

**Comment by MrMendelli** [comment]
~~Thank you for the clarification, is there anything that can be done about this, and is flashing still possible?~~

## Update

I did some more digging and I was able to find one post that states the _'RE'_ button is used to change the boot order. I will see what I can do with this later today.

**Comment by MrMendelli** [comment]
## Second Update

I have successfully entered the bootloader mode by pressing the RE button before powering the board. I do not have access to my PC currently, but I will attempt flashing later today when I do. Assuming this was all I was missing and I can flash the device, I will request this issue be closed and will also look into submitting an update to the flashing guide to specify this specific step for current Pro models in addition to other small QoL contributions I have been working on for flashing.

**Comment by MrMendelli** [comment]
## Third Update

I was able to perform the first half of the flashing process, but after removing the microSD I cannot power the board back up in bootloader mode with the RE button.

**Comment by rsglobal** [comment]
Probably, the factory bootloader is still on the EEPROM. I guess it may be a towboot. Wipe it and try again.

**Comment by rsglobal** [comment]
PPP enthusiasts aim to fix the boot order issue. Read more at https://xnux.eu/log/089.html.

**Comment by rsglobal** [comment]
I haven't tried it yet on my PPP, but it looks very promising:
https://xff.cz/kernels/rk2aw/rk2aw-rk3399-pinephone-pro/

**Comment by nonamedll** [comment]
I recently installed rk2aw and can confirm that it boots just fine.

**Comment by MrMendelli** [comment]
I have finally gotten around to installing rk2aw and u-boot in addition to GloDroid successfully.
